### ISSUE TITLE
Add Deforum animations extension

### ISSUE THREAD

**Issue by kabachuha** [NUROISEA/anime-webui-colab#10]
Hello! I think Deforum extension for Stable Diffusion animations could be particularly useful in these webui autoinstallers. It supports 2D, 3D, Video and Hybrid input modes (allow controlling any motion parameters) as well as ControlNet and other utility features, such as anime character segmentation.

https://github.com/deforum-art/deforum-for-automatic1111-webui

Anime-related examples of Deforum animations:

![20230113235807-min](https://user-images.githubusercontent.com/14872007/225018675-7cef110f-9969-4084-bd90-8fc03646a823.gif)

[20230221140916(1).webm](https://user-images.githubusercontent.com/14872007/225018582-b1f8a0f2-62e7-425e-b292-f10a20c24f1a.webm)

https://youtu.be/U9lRAyHwBiQ

**Comment by NUROISEA** [comment]
Cool extension! 😁 

I'll experiment with it for a bit and if its stable enough on Google Colab I'll add this
