### ISSUE TITLE
Stable Diffusion model failed to load, exiting.

### ISSUE THREAD

**Issue by ClydeTheMight** [NUROISEA/anime-webui-colab#19]
Hey so, when I try loading in a custom model, after providing the direct download link and VAE, when I launch the webui, it gives me this error. 
![Capture](https://user-images.githubusercontent.com/130167888/231931986-95ef3478-547f-4607-b8ee-02f0dd8d0837.PNG)

**Comment by ClydeTheMight** [comment]
Figured the problem out; I didn't put the links correctly.

**Comment by NUROISEA** [comment]
Sorry for the really late response, what link did you enter? Is the model from huggingface?

Glad that you figured it out tho, but I want "closure" 😆

**Comment by ClydeTheMight** [comment]
I accidentally linked to just the download page, not the actual download
link. Quite a stupid mistake on my part.
