### ISSUE TITLE
NameError: name 'utility' is not defined

### ISSUE THREAD

**Issue by kinjon012** [NUROISEA/anime-webui-colab#22]
NameError                                 Traceback (most recent call last)
[<ipython-input-1-a6b04e57a5e9>](https://localhost:8080/#) in <cell line: 43>()
     43 try:
---> 44   utility
     45 except NameError:

NameError: name 'utility' is not defined

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
1 frames
[/content/utility.py](https://localhost:8080/#) in log_usage(key)
     47 
     48 def log_usage(key):
---> 49   if disabled_logging:
     50     return
     51 

UnboundLocalError: local variable 'disabled_logging' referenced before assignment

**Comment by NUROISEA** [comment]
Fixed, thanks for reporting!
