### ISSUE TITLE
CamelliaMix model links inaccessible

### ISSUE THREAD

**Issue by blueberrymuffintop** [NUROISEA/anime-webui-colab#27]
So I was using the CamelliaMix model (specifically NSFW 1.1) for a couple of days and just yesterday it gave me an error message saying _stable diffusion model failed to load_ and I thought nothing of it so this morning I got up and I tried loading every other version of the model, none of them would load either and I thought okay that's obviously a problem. Then my thought was "so is it just the web UI's problem or is it like specifically this model", I tested out other models and they worked just fine and then I realized "oh it's just this model specifically".
I tried to use an ngrok token and I got the same results. I don't know what the problem is but the main messages I do get when I try to load it are _file not found_ and _stable diffusion model failed to load_. 
Maybe they changed the name of it?
![Screenshot_20230708-130840~2](https://github.com/NUROISEA/anime-webui-colab/assets/138979758/4a75e03a-2b64-4cb3-804c-fbd32076aea4)
![Screenshot_20230708-130840](https://github.com/NUROISEA/anime-webui-colab/assets/138979758/d70c7163-e729-41ce-8cd6-4f9c4294b87f)

**EDIT:** I just tried opening their HuggingFace site and nothing was there!
![Screenshot_20230708-133030](https://github.com/NUROISEA/anime-webui-colab/assets/138979758/33b24b58-bdcb-4977-83e7-ca8f66cc7190)
But! I found another model by the same name, maybe it could be a good replacement? 
![Screenshot_20230708-133200](https://github.com/NUROISEA/anime-webui-colab/assets/138979758/eb606c10-6b33-45f0-8337-c496879c1332)

**Comment by NUROISEA** [comment]
It seems like the page got taken down and the original creator uploaded the models themselves

https://huggingface.co/Mods13/CamelliaMix/tree/main

Currently AFK, but thanks for bringing this up! Will be fixed as soon as possible

**Comment by NUROISEA** [comment]
Pushed a fix
