### ISSUE TITLE
It attempted to "free" invalid pointer, thus stopping the Colab midway

### ISSUE THREAD

**Issue by DigKingy** [NUROISEA/anime-webui-colab#29]
👍 Utility script imported.
🩹 Applying Colab memory fix...
env: LD_PRELOAD=libtcmalloc.so
🔼 Selected the latest version of the web UI.
🌟 Installing stable-diffusion-webui...
🔼 Installing the latest versions of the extensions.
📦 Installing 12 extensions...
  └ aspect-ratio-preset
  └ batchlinks
  └ cutoff
  └ dynamic-thresholding
  └ images-browser
  └ latent-couple-two-shot
  └ session-organizer
  └ state
  └ tagcomplete
  └ tiled-multidiffusion-upscaler
  └ tokenizer
  └ tunnels
🔧 Fetching configs...
💉 Fetching embeddings...
🩹 Applying web UI Colab patches...
📦 Installing aria2...
⏬ Downloading MIX-Pro-V4.safetensors to /content/stable-diffusion-webui/models/Stable-diffusion...
⏬ Downloading kl-f8-anime2.ckpt to /content/stable-diffusion-webui/models/VAE...
/content/stable-diffusion-webui
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning K-diffusion into /content/stable-diffusion-webui/repositories/k-diffusion...
Cloning CodeFormer into /content/stable-diffusion-webui/repositories/CodeFormer...
Cloning BLIP into /content/stable-diffusion-webui/repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements
Installing pycloudflared

Installing ImageReward requirement for image browser

Launching Web UI with arguments: --opt-sdp-attention --lowram --no-hashing --enable-insecure-extension-access --no-half-vae --disable-safe-unpickle --gradio-queue --ckpt /content/stable-diffusion-webui/models/Stable-diffusion/MIX-Pro-V4.safetensors --vae-path /content/stable-diffusion-webui/models/VAE/kl-f8-anime2.ckpt --share
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5b96c49d7740

**Comment by NUROISEA** [comment]
For the mean time, delete the following lines of code in the notebook:
![image](https://github.com/NUROISEA/anime-webui-colab/assets/120075289/2fdc20ed-7e75-42b8-9848-b1ab34775fbd)
