### ISSUE TITLE
OrangeMix & MixPro Notebooks Disconnects Under 10 Minutes Consistently

### ISSUE THREAD

**Issue by DigKingy** [NUROISEA/anime-webui-colab#32]
👍 AOM3_orangemixs.safetensors already downloaded.
👍 orangemix.vae.pt already downloaded.
/content/stable-diffusion-webui
fatal: No names found, cannot describe anything.
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: ## 1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements

Launching Web UI with arguments: --opt-sdp-attention --lowram --no-hashing --enable-insecure-extension-access --no-half-vae --disable-safe-unpickle --gradio-queue --ckpt /content/stable-diffusion-webui/models/Stable-diffusion/AOM3_orangemixs.safetensors --vae-path /content/stable-diffusion-webui/models/VAE/orangemix.vae.pt --share
No module 'xformers'. Proceeding without it.
Image Browser: ImageReward is not installed, cannot be used.
**Loading weights [None] from /content/stable-diffusion-webui/models/Stable-diffusion/AOM3_orangemixs.safetensors**
Running on local URL:  http://127.0.0.1:7860/
preload_extensions_git_metadata for 19 extensions took 0.70s
Running on public URL: https://4099e1029036ce0944.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Startup time: 19.3s (import torch: 7.0s, import gradio: 1.1s, import ldm: 0.4s, other imports: 0.8s, load scripts: 1.5s, create ui: 1.9s, gradio launch: 6.4s).
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json: 100% 961k/961k [00:00<00:00, 9.62MB/s]
Downloading (…)olve/main/merges.txt: 100% 525k/525k [00:00<00:00, 57.6MB/s]
Downloading (…)cial_tokens_map.json: 100% 389/389 [00:00<00:00, 1.64MB/s]
Downloading (…)okenizer_config.json: 100% 905/905 [00:00<00:00, 3.74MB/s]
Downloading (…)lve/main/config.json: 100% 4.52k/4.52k [00:00<00:00, 14.5MB/s]
Loading VAE weights from commandline argument: /content/stable-diffusion-webui/models/VAE/orangemix.vae.pt
Applying attention optimization: sdp... done.
Textual inversion embeddings loaded(7): bad-artist, bad-artist-anime, bad-hands-5, bad-image-v2-39000, bad_prompt_version2, EasyNegative, EasyNegativeV2
Model loaded in 33.5s (load weights from disk: 22.9s, create model: 5.6s, load VAE: 4.5s, calculate empty prompt: 0.2s).
Couldn't find Lora with name Rabbit (wlsdnjs950)
Couldn't find Lora with name aki
Couldn't find Lora with name 3DMM_V11
  0% 0/35 [00:00<?, ?it/s]
  3% 1/35 [00:04<02:26,  4.31s/it]
  6% 2/35 [00:05<01:16,  2.33s/it]
  9% 3/35 [00:06<00:54,  1.71s/it]
 11% 4/35 [00:07<00:43,  1.40s/it]
 14% 5/35 [00:08<00:36,  1.20s/it]
 17% 6/35 [00:08<00:31,  1.09s/it]
 20% 7/35 [00:09<00:28,  1.01s/it]
 23% 8/35 [00:10<00:25,  1.06it/s]
 26% 9/35 [00:11<00:23,  1.11it/s]
 29% 10/35 [00:12<00:21,  1.14it/s]
 31% 11/35 [00:12<00:20,  1.16it/s]
 34% 12/35 [00:13<00:19,  1.18it/s]
 37% 13/35 [00:14<00:18,  1.19it/s]
 40% 14/35 [00:15<00:17,  1.20it/s]
 43% 15/35 [00:16<00:16,  1.21it/s]
 46% 16/35 [00:17<00:15,  1.21it/s]
 49% 17/35 [00:17<00:14,  1.21it/s]
 51% 18/35 [00:18<00:14,  1.21it/s]
 54% 19/35 [00:19<00:13,  1.20it/s]
 57% 20/35 [00:20<00:12,  1.19it/s]
 60% 21/35 [00:21<00:11,  1.19it/s]
 63% 22/35 [00:22<00:10,  1.19it/s]
 66% 23/35 [00:22<00:10,  1.17it/s]
 69% 24/35 [00:23<00:09,  1.18it/s]
 71% 25/35 [00:24<00:08,  1.17it/s]
 74% 26/35 [00:25<00:07,  1.17it/s]
 77% 27/35 [00:26<00:06,  1.18it/s]
 80% 28/35 [00:27<00:05,  1.19it/s]
 83% 29/35 [00:28<00:05,  1.19it/s]
 86% 30/35 [00:28<00:04,  1.20it/s]
 89% 31/35 [00:29<00:03,  1.21it/s]
 91% 32/35 [00:30<00:02,  1.21it/s]
 94% 33/35 [00:31<00:01,  1.21it/s]
 97% 34/35 [00:32<00:00,  1.22it/s]
100% 35/35 [00:32<00:00,  1.08it/s]

Total progress: 100% 35/35 [00:45<00:00,  1.30s/it]
{"prompt": "<lora:Rabbit (wlsdnjs950):0.8> <lora:aki:0.3>  <lora:3DMM_V11:0.5> 3d, thick eyebrows, gradient, gradient background, barefoot, standing, petite, little female, smile, \n", "all_prompts": ["<lora:Rabbit (wlsdnjs950):0.8> <lora:aki:0.3>  <lora:3DMM_V11:0.5> 3d, thick eyebrows, gradient, gradient background, barefoot, standing, petite, little female, smile, \n"], "negative_prompt": "(worst quality, low quality:1.4) Poorly Made Bad 3D, Lousy Bad Realistic, bad anatomy, bad hands, extra fingers, fewer fingers,\n", "all_negative_prompts": ["(worst quality, low quality:1.4) Poorly Made Bad 3D, Lousy Bad Realistic, bad anatomy, bad hands, extra fingers, fewer fingers,\n"], "seed": 2434781936, "all_seeds": [2434781936], "subseed": 953420483, "all_subseeds": [953420483], "subseed_strength": 0, "width": 560, "height": 1024, "sampler_name": "DPM++ SDE Karras", "cfg_scale": 6.5, "steps": 35, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": null, "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {}, "index_of_first_image": 0, "infotexts": ["<lora:Rabbit (wlsdnjs950):0.8> <lora:aki:0.3>  <lora:3DMM_V11:0.5> 3d, thick eyebrows, gradient, gradient background, barefoot, standing, petite, little female, smile, \n\nNegative prompt: (worst quality, low quality:1.4) Poorly Made Bad 3D, Lousy Bad Realistic, bad anatomy, bad hands, extra fingers, fewer fingers,\n\nSteps: 35, Sampler: DPM++ SDE Karras, CFG scale: 6.5, Seed: 2434781936, Size: 560x1024, Model: AOM3_orangemixs, RNG: CPU, Version: ## 1.4.0"], "styles": [], "job_timestamp": "20230911015418", "clip_skip": 1, "is_using_inpainting_conditioning": false}
loading Lora /content/stable-diffusion-webui/models/Lora/Rabbit (wlsdnjs950).safetensors: SafetensorError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 253, in load_loras
    lora = load_lora(name, lora_on_disk)
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 162, in load_lora
    sd = sd_models.read_state_dict(lora_on_disk.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 250, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

loading Lora /content/stable-diffusion-webui/models/Lora/porforever_v1.0.safetensors: SafetensorError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 253, in load_loras
    lora = load_lora(name, lora_on_disk)
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 162, in load_lora
    sd = sd_models.read_state_dict(lora_on_disk.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 250, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**loading Lora /content/stable-diffusion-webui/models/Lora/3DMM_V11.safetensors: SafetensorError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 253, in load_loras
    lora = load_lora(name, lora_on_disk)
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 162, in load_lora
    sd = sd_models.read_state_dict(lora_on_disk.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 250, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer**

  0% 0/35 [00:00<?, ?it/s]
  3% 1/35 [00:00<00:29,  1.15it/s]
  6% 2/35 [00:01<00:29,  1.13it/s]
  9% 3/35 [00:02<00:28,  1.14it/s]
 11% 4/35 [00:03<00:26,  1.15it/s]
 14% 5/35 [00:04<00:26,  1.14it/s]
 17% 6/35 [00:05<00:25,  1.14it/s]
 20% 7/35 [00:06<00:24,  1.15it/s]
 23% 8/35 [00:06<00:23,  1.15it/s]
 26% 9/35 [00:07<00:22,  1.15it/s]
 29% 10/35 [00:08<00:21,  1.15it/s]
 31% 11/35 [00:09<00:20,  1.14it/s]
 34% 12/35 [00:10<00:20,  1.15it/s]
 37% 13/35 [00:11<00:19,  1.12it/s]
 40% 14/35 [00:12<00:18,  1.12it/s]
 43% 15/35 [00:13<00:17,  1.11it/s]
 46% 16/35 [00:14<00:17,  1.10it/s]
 49% 17/35 [00:15<00:16,  1.09it/s]
 51% 18/35 [00:15<00:15,  1.10it/s]
 54% 19/35 [00:16<00:14,  1.10it/s]
 57% 20/35 [00:17<00:13,  1.10it/s]
 60% 21/35 [00:18<00:12,  1.11it/s]
 63% 22/35 [00:19<00:11,  1.12it/s]
 66% 23/35 [00:20<00:10,  1.13it/s]
 69% 24/35 [00:21<00:09,  1.14it/s]
 71% 25/35 [00:22<00:08,  1.15it/s]
 74% 26/35 [00:23<00:07,  1.15it/s]
 77% 27/35 [00:23<00:06,  1.16it/s]
 80% 28/35 [00:24<00:06,  1.15it/s]
 83% 29/35 [00:25<00:05,  1.16it/s]
 86% 30/35 [00:26<00:04,  1.14it/s]
 89% 31/35 [00:27<00:03,  1.15it/s]
 91% 32/35 [00:28<00:02,  1.15it/s]
 94% 33/35 [00:29<00:01,  1.15it/s]
 97% 34/35 [00:29<00:00,  1.16it/s]
100% 35/35 [00:30<00:00,  1.15it/s]

**Comment by DigKingy** [comment]
Note: The Lora's I have loaded were not even registered within the Notebook, leaving no effect towards the diffusion whatsoever.

**Comment by NUROISEA** [comment]
> Error while deserializing header: MetadataIncompleteBuffer

What LoRAs are you using? I assume that you are downloading it via Batchlinks? I tested it with my favorite LoRAs, and all of which works, probably a problem on your downloaded LoRAs.

----

About the 10 minutes, yeah I experience it too for some reason. This is probably Colab's way of limiting usage, I have no control over this.

**Comment by DigKingy** [comment]
LoRA's: <lora:Rabbit (wlsdnjs950):0.8><lora:aki:0.3><lora:3DMM_V11:0.5><lora:add_detail:0.6>

These are the LoRA's I would use in order to diffuse different pieces of media. Yet, maybe around 2 minutes of implementing them into the system, it would give me the error below. 👇 

**"loading Lora /content/stable-diffusion-webui/models/Lora/3DMM_V11.safetensors: SafetensorError
Traceback (most recent call last):
File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 253, in load_loras
lora = load_lora(name, lora_on_disk)
File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 162, in load_lora
sd = sd_models.read_state_dict(lora_on_disk.filename)
File "/content/stable-diffusion-webui/modules/sd_models.py", line 250, in read_state_dict
pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer"**

But that's the thing, it doesn't screw up until I add the LoRA's, but if I just use the model as is, no problems occur.
