### ISSUE TITLE
Colab Notebooks Disconnect Within A Few Seconds, Repetitively

### ISSUE THREAD

**Issue by DigKingy** [NUROISEA/anime-webui-colab#33]
👍 Utility script imported.
🌟 Installing stable-diffusion-webui...
📦 Installing 12 extensions...
  └ aspect-ratio-preset
  └ batchlinks
  └ cutoff
  └ dynamic-thresholding
  └ images-browser
  └ latent-couple-two-shot
  └ session-organizer
  └ state
  └ tagcomplete
  └ tiled-multidiffusion-upscaler
  └ tokenizer
  └ tunnels
🔧 Fetching configs...
💉 Fetching embeddings...
🩹 Applying web UI Colab patches...
🩹 Applying Colab memory patches...
env: LD_PRELOAD=/content/libtcmalloc_minimal.so.4
📦 Installing aria2...

Then the cell would disconnect. I would also try other notebooks, but they all had around the same result, disconnecting with a few seconds. Maybe it could be my connection, but I doubt it due to my connection being at full bars consistently. It's not the ram usage either which is an issue you fixed successfully. So I am genuinely confused on why the notebooks disconnect so incredibly quick.

**Comment by joyarup** [comment]
Yeah, same issue here, the runtime will disconnect randomly doesn't matter which line it is running or which extension it is installing. Tried with different notebooks with different colab accounts, same result.

**Comment by NUROISEA** [comment]
It seems like the check for the webui is server sided.

Google Colab's team is really pushing for no webui usage on their platform, unfortunately I cannot do anything to circumvent it.

Buying Colab Pro could perhaps prevent those disconnects? I'm not too sure. :/

**Comment by DigKingy** [comment]
So essentially the possibility of Webui being used on Google Colab seems to not be reliable in the future of using Google Colab?

**Comment by NUROISEA** [comment]
> So essentially the possibility of Webui being used on Google Colab seems to not be reliable in the future of using Google Colab?

Yes, unless you pay for Pro.

But who knows, maybe they would be lenient in the future. As it stands, web UI on Colab is pretty much dead.
