### ISSUE TITLE
Gradio doesn't work and cannot download from huggingface

### ISSUE THREAD

**Issue by ErickFRL** [NUROISEA/anime-webui-colab#44]
I get this error when I try to download a Hugging Face model in the first cell.

![imagen_2024-05-01_100338542](https://github.com/NUROISEA/anime-webui-colab/assets/149989164/fe12c331-45a6-481a-b9e7-e6155dffa1ef)

 On the other hand, when I try to load a Civitai model, it manages to load everything, but in the end the public link does not appear.
 
 ![imagen_2024-05-01_101810134](https://github.com/NUROISEA/anime-webui-colab/assets/149989164/fce35b80-4f8b-438c-9477-349394681e8c)

**Comment by NUROISEA** [comment]
Fixed the downloader.

And yeah, gradio doesn't seem to work right now.

Try using ngrok for the meantime?

**Comment by ErickFRL** [comment]
I tried with gradio and it worked, thanks for everything.
