### ISSUE TITLE
Error while downloading OrangeMixs models

### ISSUE THREAD

**Issue by ArakiSatoshi** [NUROISEA/anime-webui-colab#9]
They updated the names of their [AbyssOrangeMix3](https://huggingface.co/WarriorMama777/OrangeMixs/tree/main/Models/AbyssOrangeMix3) models on HuggingFace, so Colab is unable to download them.

In Colab, manually changing the line to this (or any other OrangeMixs model):

`model = "AbyssOrangeMix3/AOM3A1B_orangemixs.safetensors"`

Resolves the issue.

**Comment by NUROISEA** [comment]
...they changed it again? fixing asap, thanks for pointing it out
